# Generated by Django 6.0.6 on 2026-06-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='test_taker_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='assessment',
            name='test_taker_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
