# Generated by Django 6.0.6 on 2026-06-22 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PathwayRelevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_name', models.CharField(max_length=50)),
                ('relevance_score', models.FloatField()),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.pathway')),
            ],
        ),
        migrations.CreateModel(
            name='PathwayScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_score', models.FloatField()),
                ('preference_score', models.FloatField()),
                ('final_score', models.FloatField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.pathway')),
            ],
        ),
    ]
